# Generated by Django 5.1.3 on 2024-12-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_event_link_publication_link_talk_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
