# Generated by Django 5.1.3 on 2024-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='../media/content/img/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='../media/content/img/'),
        ),
    ]
