# Generated by Django 5.1.3 on 2024-12-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_homepagecontent_text2_alter_homepagecontent_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='photo3_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='content/img'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='photo4_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='content/img'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='photo5_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='content/img'),
        ),
    ]
